#!/bin/bash

if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
  echo "$0 [ <test_flag1> <test_flag2> ... ]" >&2
  exit 1
fi

clear
CPUS="`grep processor /proc/cpuinfo  | wc -l`"
time make "-j$CPUS" test && ( cd gen/gcc/test/ && LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../libs" time ./*.t "$@" )
